
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'testAtest : __zero_or_one_A__zero_or_one_A : A \n                       |'
    
_lr_action_items = {'A':([0,],[3,]),'$end':([0,1,2,3,],[-3,0,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'test':([0,],[1,]),'__zero_or_one_A':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> test","S'",1,None,None,None),
  ('test -> __zero_or_one_A','test',1,'p_test','zero_or_one.py',22),
  ('__zero_or_one_A -> A','__zero_or_one_A',1,'p___zero_or_one_A','zero_or_one.py',26),
  ('__zero_or_one_A -> <empty>','__zero_or_one_A',0,'p___zero_or_one_A','zero_or_one.py',27),
]
