
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE MINUS NUMBER PLUS TIMESexpression : expression MINUS termexpression : expression PLUS termexpression : termfactor : NUMBERterm : term DIVIDE factorterm : factorterm : term TIMES factor'
    
_lr_action_items = {'NUMBER':([0,5,6,7,8,],[4,4,4,4,4,]),'$end':([1,2,3,4,9,10,11,12,],[0,-3,-6,-4,-1,-2,-5,-7,]),'MINUS':([1,2,3,4,9,10,11,12,],[5,-3,-6,-4,-1,-2,-5,-7,]),'PLUS':([1,2,3,4,9,10,11,12,],[6,-3,-6,-4,-1,-2,-5,-7,]),'DIVIDE':([2,3,4,9,10,11,12,],[7,-6,-4,7,7,-5,-7,]),'TIMES':([2,3,4,9,10,11,12,],[8,-6,-4,8,8,-5,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),'term':([0,5,6,],[2,9,10,]),'factor':([0,5,6,7,8,],[3,3,3,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression MINUS term','expression',3,'p_p_expression_minus','generate_ast.py',35),
  ('expression -> expression PLUS term','expression',3,'p_p_expression_plus','generate_ast.py',35),
  ('expression -> term','expression',1,'p_p_expression_term','generate_ast.py',35),
  ('factor -> NUMBER','factor',1,'p_p_factor_number','generate_ast.py',35),
  ('term -> term DIVIDE factor','term',3,'p_p_term_divide','generate_ast.py',35),
  ('term -> factor','term',1,'p_p_term_factor','generate_ast.py',35),
  ('term -> term TIMES factor','term',3,'p_p_term_times','generate_ast.py',35),
]
